### DISCUSSION TITLE
How to convert PSB (R,G,B,IR) to BigTIFF ?

### DISCUSSION THREAD

**Discussion by Aladar2021** [ImageMagick/ImageMagick#3095] [Help]
How to convert Photoshop Large Document format (PSB) with 4 channels (Red, Green, Blue and InfraRed) to BigTIFF ? 

_convert Input_RGBIR.psb TIFF64:Output_RGBIR.tif:_
output image contains strange histogram values for each channel and the image does not look like original one.

(Note: If input PSB is 3 channel RGB then output BigTIFF is ok.)

**Comment by urban-warrior** [comment]
Post a link to one or two PSB image samples.  We need to download and inspect them before we can help further.

**Comment by dlemstra** [comment]
And next time please don't create both a discussion and an issue.

**Comment by Aladar2021** [comment]
Input PSB:
http://s000.tinyupload.com/index.php?file_id=56807581717214445922

Output BigTIFF:
http://s000.tinyupload.com/index.php?file_id=60612674125225755876

Thank you very much.

**Comment by Aladar2021** [comment]
Output BigTIFF is expected to have R,G,B,IR and should look like this (with RGB turned on):

![Output_OK](https://user-images.githubusercontent.com/77156028/104302992-c7ab8b00-54c9-11eb-929d-84cddf2a84ba.jpg)

and with IR on it should look like this:
![Output_OK_IR](https://user-images.githubusercontent.com/77156028/104303467-6a640980-54ca-11eb-8498-a2c0bc0f3f14.jpg)

**Comment by urban-warrior** [comment]
IR and RGB are two separate energy spectrums.  It likely does not sense to mix them.  We could separate out the IR from the RGB into separate images, one RGB, the other IR.  We could capture the IR channel in TIFF and not identify it as alpha.  The image above does not look like a true IR spectrum. We could false color the IR channel to produce something like your image above.  We would need references to algorithms for false coloring an IR channel before we could investigate further.  @fmw42, how much of what I just said is bogus?  And what do you recommend?

**Reply by fmw42** [reply]
My suggestion is to capture the IR channel and save it in the output TIFF alpha channel. Afterwards the user can merge the RGB channels with some constant color image using the alpha channel as a mask. I would also recommend if the input TIFF has more than one extra channel to have some way to select which one to choose as the alpha channel to apply in the output TIFF. For example, -define tiff:which-alpha=4 (must be 4 or larger). I think all of this would require you to finish what we discussed a long while back about saving Photoshop files with extra channels to a TIFF with one or more extra channels, using one of them as an alpha channel if desired. So you need a way to decide if all extra channels will be simply copied or if one should be designed as the alpha channel for transparency or just one saved as the alpha channel and the rest discarded. 

The problem I see is how to copy any extra channel from the input. In my testing, none of the extra channels can be exported, since they are always disabled when saving.

**@Magick**  Contact me offline and we can discuss further.

**Comment by Aladar2021** [comment]
I have tested ImageMagick 7.0.10-62 Q16 x64, the output image is still not ok :(

**Comment by snibgo** [comment]
Using IM v7.0.10-45 ...
```
magick Input_RGBIR.psb -verbose info:x.txt
```
... we see the channels have strange values:
```
    Red:
      min: -64770  (-254)
      max: 255 (1)
      mean: -283.875 (-1.11323)
      median: -59.8696 (-0.234783)
      standard deviation: 1514.1 (5.93766)
      kurtosis: 896.174
      skewness: -25.4804
      entropy: 0.286265
    Green:
      min: -64770  (-254)
      max: 255 (1)
      mean: -266.982 (-1.04699)
      median: -52.2541 (-0.204918)
      standard deviation: 1439.97 (5.64692)
      kurtosis: 902.983
      skewness: -25.5874
      entropy: 0.305226
    Blue:
      min: -59670  (-234)
      max: 255 (1)
      mean: -263.763 (-1.03436)
      median: -73.9695 (-0.290076)
      standard deviation: 1313.53 (5.15108)
      kurtosis: 909.807
      skewness: -25.6973
      entropy: 0.232143
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 121.341 (0.475847)
```
The alpha (IR) channel looks sensible, but the RGB channels range from -254 to +1.0, on a nominal scale of 0.0 to 1.0. The mean values are negative. So what do those values represent? Do you have some documentation that describes the file?

We can use "-auto-level -auto-scale" to make the values more sensible, but that processing is probably "wrong".
