### DISCUSSION TITLE
Documentation website: list of cli options layout

### DISCUSSION THREAD

**Discussion by royemosby** [ImageMagick/ImageMagick#6691] [Contribute]
### Is your feature request related to a problem? Please describe.

Refering to: https://imagemagick.org/script/command-line-options.php

The current <p> full of command line options is hard to read through. Even though they are in alphabetic order, they are tight together and makes visual searching difficult.
![output3](https://user-images.githubusercontent.com/10133316/148684583-7937d7ac-373e-4567-b042-fa3c0d4fe33d.jpg)

### Describe the solution you'd like

They would be much easier to read in a grid-style format. The image below illustrates the following css applied:

```css
p.text-center {
    display: grid;
    grid-template-columns: 1fr 1em 1fr 2em 1fr 2em 1fr 2em;
    text-align: left !important;
}
p.text-center:nth-child(even){
    color: white;
```
![output2](https://user-images.githubusercontent.com/10133316/148684658-61c8d660-07ab-46ff-a7e6-fbfe7b37b3b8.jpg)
