### ISSUE TITLE
can't replace color with transparency on windows(but working on linux)

### ISSUE THREAD

**Issue by jestarray** [ImageMagick/ImageMagick#2656]
### Description
when running 
```
convert 00.png -transparent '#c0c0c0' 01.png
```
on the following image:

![00](https://user-images.githubusercontent.com/34615798/94847627-b1c10100-03d7-11eb-8c53-9a0064a77282.png)

it doesn't do anything on **Windows 10** but it **works on linux**

Windows 10, ImageMagick version 7.0.10-14 ; 2020-05-23 ~~(I can't update it right now because the download page is down https://imagemagick.org/script/download.php , says file not found at the time of writing this)~~

edit: This also happens on latest version : 7.0.10-29 Q16 x64

**Comment by fmw42** [comment]
Use double quotes on Windows.

**Comment by jestarray** [comment]
Even if I use double quote on windows, it doesn't remove the transparency for me.... It's this specific color that doesn't work on windows.

**Comment by fmw42** [comment]
-transparent does not remove transparency, it changes that color to transparent. +transparent does not remove transparency either. It makes all colors but the listed color as transparent.

**Comment by jestarray** [comment]
Woops yeah, It's not replacing the color to transparent* for me on windows. Is this reproducible on your end?

**Comment by fmw42** [comment]
You should probably add -fuzz XX% before -transparent. Colors may be slightly off from what you think they are. I have seen different results from different tools that claim to measure hex colors.

**Comment by jestarray** [comment]
yeah, even with fuzz it doesn't work at all. Its strange though because this works absolutely fine on linux without fuzz. If I need
 `-fuzz` on windows, shouldn't the same be for linux?
Here is a video:
https://streamable.com/jmmlpc

**Comment by snibgo** [comment]
It works fine for me, with IM v7.0.8-64 (an v7.0.10-27) on Windows 8.1.

I'm not familiar with Paintnet. Does it show transparency?

```
f:\web\im>%IMG7%magick 94847627-b1c10100-03d7-11eb-8c53-9a0064a77282.png -transparent #c0c0c0 x.png

f:\web\im>%IMG7%magick x.png -verbose info:

:
:
    Pixels: 1024
    Gray:
      min: 192  (0.752941)
      max: 192 (0.752941)
      mean: 192 (0.752941)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
    Alpha:
      min: 0  (0)
      max: 0 (0)
      mean: 0 (0)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
  Alpha: graya(192,0)   #C0C0C000
  Colors: 1
  Histogram:
      1024: (192,192,192,  0) #C0C0C000 graya(192,0)
```
The result is a single colour, #C0C0C000, fully-transparent gray. Fuzz is not needed.
