### ISSUE TITLE
possible issue converting 8-bit/channel png to 32-bit/channel tif

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#4418]
### ImageMagick version

7.1.0.11

### Operating system

MacOS

### Operating system, version and so on

OSX Sierra

### Description

I am trying to convert an 8-bit per channel color png to 32/8-bit per channel tif. There are several issues. 

Are these bugs or do I not understand how quantum range is scaled?

```
1) The result ends up 16/8-bit per channel and not 32/8-bit per channel

2) The ranges of min and max for each channel are not scaled properly. 
0 and 255 in the 8-bit input does not end up 0 and 65535 in the 16-bit output

input green min = 29  but output green min = 0
input blue min = 29  but output blue min = 0

input red max = 255  but output red max = 60395 and should be 65535
input green max = 255  but output green max = 22102 and should be 65535
input blue max = 255  but output blue max = 25957 and should be 65535

```

Input:

![GRID7](https://user-images.githubusercontent.com/13458218/139337542-6e939c44-976e-4b66-b1e6-232b3ebce231.png)

```
magick GRID7.png -verbose info:

 Depth: 8-bit
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
  Channel statistics:
    Pixels: 2560000
    Red:
      min: 0  (0)
      max: 255 (1)
    Green:
      min: 29  (0.113725)
      max: 255 (1)
    Blue:
      min: 29  (0.113725)
      max: 255 (1)

```

Using Q32 HDRI IM 7.1.0.11

`magick -define quantum:format=floating-point GRID7.png GRID7.tif`

[GRID7.tif.zip](https://github.com/ImageMagick/ImageMagick/files/7437406/GRID7.tif.zip)

`magick -define quantum:format=floating-point GRID7.tif -verbose info:`

```
 Depth: 16/8-bit
  Channel statistics:
    Pixels: 2560000
    Red:
      min: 0  (0)
      max: 60395 (0.92156863)
    Green:
      min: 0  (0)
      max: 22102 (0.3372549)
     Blue:
      min: 0  (0)
      max: 25957 (0.39607843)

```

### Steps to Reproduce

See above

### Images

See above
