### ISSUE TITLE
Support uhdr in `identify`

### ISSUE THREAD

**Issue by eddy-geek** [ImageMagick/ImageMagick#7908]
### Is your feature request related to a problem? Please describe.

Current situation, assuming some_hdr.jpg is an HDR image with gain map like [this sample](https://github.com/MishaalRahmanGH/Ultra_HDR_Samples/raw/main/Originals/Ultra_HDR_Samples_Originals_01.jpg):

1. `magick identify -verbose some_hdr.jpg` does not the uhdr delegate so it only shows information on the base SDR image and the only way to "recognize" an UHDR image may be to pick on the some of the extra "profiles":
```
   Profiles:
     Profile-app1: 79944 bytes
     Profile-exif: 30219 bytes
     Profile-icc: 596 bytes
     Profile-mpf: 670 bytes
     Profile-xmp: 1034 bytes
```

2. `magick identify uhdr:some_hdr.jpg` gives an error:
 `invalid output color transfer -1, ... error/uhdr.c/ReadUHDRImage/196`
I would not expect to have to provide this to get basic image information...

3. `magick identify -verbose -define uhdr:output-color-transfer=srgb uhdr:some_hdr.jpg`
finally works... but provides even less information ! There is now no JPG quality at all, not even that of the SDR base image.

(Cc #6377)

### Describe the solution you'd like

There should be a way to find out from `identify`:

* if the image has gain map(s), in which format (ISO or not), with what transformation
* size of the gain map vs size of base image
* format & jpg quality of the gain map if applicable

ideally, do so without requiring to be explicitly adding `uhdr:`, I expect that `identify` should help me "identify" it's needed ;-)
